name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show OS
        run: uname -a

      - name: Show hostname
        run: hostname

      - name: Show current user
        run: whoami
         
         
